### ISSUE TITLE
请问一下这个IAST attach上java进程后，有办法detach吗？

### ISSUE THREAD

**Issue by wouijvziqy** [keven1z/simpleIAST#2]
当使用完IAST后，希望能够detach

**Comment by keven1z** [comment]
目前只能通过重启来卸载，近期会增加动态卸载IAST

**Comment by keven1z** [comment]
已添加动态卸载，https://github.com/keven1z/simpleIAST/commit/11c9e43ae1c0fa91608358287b0e581aab7b416a
